/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as PublicLoginIndexRouteImport } from './pages/_public/login/index'
import { Route as PublicSigninAndSignupIndexRouteImport } from './pages/_public/SigninAndSignup/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/_public/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSigninAndSignupIndexRoute =
  PublicSigninAndSignupIndexRouteImport.update({
    id: '/_public/SigninAndSignup/',
    path: '/SigninAndSignup/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/SigninAndSignup': typeof PublicSigninAndSignupIndexRoute
  '/login': typeof PublicLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/SigninAndSignup': typeof PublicSigninAndSignupIndexRoute
  '/login': typeof PublicLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public/SigninAndSignup/': typeof PublicSigninAndSignupIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/SigninAndSignup' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/SigninAndSignup' | '/login'
  id: '__root__' | '/' | '/_public/SigninAndSignup/' | '/_public/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicSigninAndSignupIndexRoute: typeof PublicSigninAndSignupIndexRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/SigninAndSignup/': {
      id: '/_public/SigninAndSignup/'
      path: '/SigninAndSignup'
      fullPath: '/SigninAndSignup'
      preLoaderRoute: typeof PublicSigninAndSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicSigninAndSignupIndexRoute: PublicSigninAndSignupIndexRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
