/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PrivateIndexRouteImport } from './pages/_private/index'
import { Route as PublicLoginIndexRouteImport } from './pages/_public/login/index'
import { Route as PrivatePokemonsIndexRouteImport } from './pages/_private/pokemons/index'

const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/_private/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/_public/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatePokemonsIndexRoute = PrivatePokemonsIndexRouteImport.update({
  id: '/_private/pokemons/',
  path: '/pokemons/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/pokemons': typeof PrivatePokemonsIndexRoute
  '/login': typeof PublicLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/pokemons': typeof PrivatePokemonsIndexRoute
  '/login': typeof PublicLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private/': typeof PrivateIndexRoute
  '/_private/pokemons/': typeof PrivatePokemonsIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemons' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemons' | '/login'
  id: '__root__' | '/_private/' | '/_private/pokemons/' | '/_public/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivatePokemonsIndexRoute: typeof PrivatePokemonsIndexRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/pokemons/': {
      id: '/_private/pokemons/'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof PrivatePokemonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivatePokemonsIndexRoute: PrivatePokemonsIndexRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
